### ISSUE TITLE
Hyphens

### ISSUE THREAD

**Issue by snowztail** [lintalist/TitleCase#1]
Dear Sir or Madam,

This is indeed a great project. Would you mind adding support for words including hyphens? For example, "Low-Power" rather than "Low-power". 

Thanks for your attention.

**Comment by snowztail** [comment]
... and words as "Internet-of-Things" may need extra care.

**Comment by lintalist** [comment]
Good idea , you can try beta 1.3 here https://github.com/lintalist/TitleCase/tree/beta - you can adjust your preferences by editing the new INI hyphen1 and hyphen2 find-replace keys

Hyphen1 changes "Low-power" to "Low-Power"
Hyphen2 fixes "Internet-Of-Things" to "Internet-of-Things" and a few other variations

**Comment by snowztail** [comment]
Sadly it doesn't work for me somehow... I didn't make any change and both lists seems not working (Low-power and Internet-of-things).

I apologize for having totally no idea about scripts. Thank you for support ❤️

**Comment by lintalist** [comment]
Be sure to download the beta titlecase.ahk not the master and if you have only replaced titlecase.ahk but kept on using the same titlecase.ini you currently/previously had you need to update it and add some keys manually. 

```ini
OrdinalIndicator_Find=im)\b(\d+)(st|nd|rd|th)\b
OrdinalIndicator_Replace=$1$L{2}
Hypen1_Find=im)-\K(.)
Hypen1_Replace=$U{1}
Hypen2_Find=im)-(and|but|for|nor|of|or|so|yet)-
Hypen2_Replace=-$L{1}-
```

TitleCase will create a new titlecase.ini if you rename or delete the current one (make sure you have a backup if you changed the default values or added other data of course)

My results:

In:
> AUTOHOTKEY IS THE 1ST SCRIPTING LANGUAGE ... USER-CONTRIBUTED FEATURES LOW-POWER AND INTERNET-OF-THINGS.

out:
> AutoHotkey is the **1st** Scripting Language ... **User-Contributed** Features **Low-Power** and **Internet-of-Things**.

**Comment by snowztail** [comment]
My sincere appreciate for your help. 

I believe this should work and the problem could be with my own function.

Thank you and wish you a nice week.
